// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_frame.proto

#ifndef PROTOBUF_INCLUDED_video_5fframe_2eproto
#define PROTOBUF_INCLUDED_video_5fframe_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_video_5fframe_2eproto 

namespace protobuf_video_5fframe_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_video_5fframe_2eproto
class VideoFrame;
class VideoFrameDefaultTypeInternal;
extern VideoFrameDefaultTypeInternal _VideoFrame_default_instance_;
namespace google {
namespace protobuf {
template<> ::VideoFrame* Arena::CreateMaybeMessage<::VideoFrame>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class VideoFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:VideoFrame) */ {
 public:
  VideoFrame();
  virtual ~VideoFrame();

  VideoFrame(const VideoFrame& from);

  inline VideoFrame& operator=(const VideoFrame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VideoFrame(VideoFrame&& from) noexcept
    : VideoFrame() {
    *this = ::std::move(from);
  }

  inline VideoFrame& operator=(VideoFrame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VideoFrame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VideoFrame* internal_default_instance() {
    return reinterpret_cast<const VideoFrame*>(
               &_VideoFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(VideoFrame* other);
  friend void swap(VideoFrame& a, VideoFrame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VideoFrame* New() const final {
    return CreateMaybeMessage<VideoFrame>(NULL);
  }

  VideoFrame* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VideoFrame>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VideoFrame& from);
  void MergeFrom(const VideoFrame& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes frame_data = 5;
  void clear_frame_data();
  static const int kFrameDataFieldNumber = 5;
  const ::std::string& frame_data() const;
  void set_frame_data(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_data(::std::string&& value);
  #endif
  void set_frame_data(const char* value);
  void set_frame_data(const void* value, size_t size);
  ::std::string* mutable_frame_data();
  ::std::string* release_frame_data();
  void set_allocated_frame_data(::std::string* frame_data);

  // string delivered_from = 6;
  void clear_delivered_from();
  static const int kDeliveredFromFieldNumber = 6;
  const ::std::string& delivered_from() const;
  void set_delivered_from(const ::std::string& value);
  #if LANG_CXX11
  void set_delivered_from(::std::string&& value);
  #endif
  void set_delivered_from(const char* value);
  void set_delivered_from(const char* value, size_t size);
  ::std::string* mutable_delivered_from();
  ::std::string* release_delivered_from();
  void set_allocated_delivered_from(::std::string* delivered_from);

  // int64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // int32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // int32 height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // int32 channels = 4;
  void clear_channels();
  static const int kChannelsFieldNumber = 4;
  ::google::protobuf::int32 channels() const;
  void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:VideoFrame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr frame_data_;
  ::google::protobuf::internal::ArenaStringPtr delivered_from_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 channels_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_video_5fframe_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VideoFrame

// int64 timestamp = 1;
inline void VideoFrame::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 VideoFrame::timestamp() const {
  // @@protoc_insertion_point(field_get:VideoFrame.timestamp)
  return timestamp_;
}
inline void VideoFrame::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.timestamp)
}

// int32 width = 2;
inline void VideoFrame::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 VideoFrame::width() const {
  // @@protoc_insertion_point(field_get:VideoFrame.width)
  return width_;
}
inline void VideoFrame::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.width)
}

// int32 height = 3;
inline void VideoFrame::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 VideoFrame::height() const {
  // @@protoc_insertion_point(field_get:VideoFrame.height)
  return height_;
}
inline void VideoFrame::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.height)
}

// int32 channels = 4;
inline void VideoFrame::clear_channels() {
  channels_ = 0;
}
inline ::google::protobuf::int32 VideoFrame::channels() const {
  // @@protoc_insertion_point(field_get:VideoFrame.channels)
  return channels_;
}
inline void VideoFrame::set_channels(::google::protobuf::int32 value) {
  
  channels_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.channels)
}

// bytes frame_data = 5;
inline void VideoFrame::clear_frame_data() {
  frame_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VideoFrame::frame_data() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_data)
  return frame_data_.GetNoArena();
}
inline void VideoFrame::set_frame_data(const ::std::string& value) {
  
  frame_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_data)
}
#if LANG_CXX11
inline void VideoFrame::set_frame_data(::std::string&& value) {
  
  frame_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:VideoFrame.frame_data)
}
#endif
inline void VideoFrame::set_frame_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  frame_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:VideoFrame.frame_data)
}
inline void VideoFrame::set_frame_data(const void* value, size_t size) {
  
  frame_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:VideoFrame.frame_data)
}
inline ::std::string* VideoFrame::mutable_frame_data() {
  
  // @@protoc_insertion_point(field_mutable:VideoFrame.frame_data)
  return frame_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFrame::release_frame_data() {
  // @@protoc_insertion_point(field_release:VideoFrame.frame_data)
  
  return frame_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFrame::set_allocated_frame_data(::std::string* frame_data) {
  if (frame_data != NULL) {
    
  } else {
    
  }
  frame_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_data);
  // @@protoc_insertion_point(field_set_allocated:VideoFrame.frame_data)
}

// string delivered_from = 6;
inline void VideoFrame::clear_delivered_from() {
  delivered_from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VideoFrame::delivered_from() const {
  // @@protoc_insertion_point(field_get:VideoFrame.delivered_from)
  return delivered_from_.GetNoArena();
}
inline void VideoFrame::set_delivered_from(const ::std::string& value) {
  
  delivered_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:VideoFrame.delivered_from)
}
#if LANG_CXX11
inline void VideoFrame::set_delivered_from(::std::string&& value) {
  
  delivered_from_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:VideoFrame.delivered_from)
}
#endif
inline void VideoFrame::set_delivered_from(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  delivered_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:VideoFrame.delivered_from)
}
inline void VideoFrame::set_delivered_from(const char* value, size_t size) {
  
  delivered_from_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:VideoFrame.delivered_from)
}
inline ::std::string* VideoFrame::mutable_delivered_from() {
  
  // @@protoc_insertion_point(field_mutable:VideoFrame.delivered_from)
  return delivered_from_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFrame::release_delivered_from() {
  // @@protoc_insertion_point(field_release:VideoFrame.delivered_from)
  
  return delivered_from_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFrame::set_allocated_delivered_from(::std::string* delivered_from) {
  if (delivered_from != NULL) {
    
  } else {
    
  }
  delivered_from_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), delivered_from);
  // @@protoc_insertion_point(field_set_allocated:VideoFrame.delivered_from)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_video_5fframe_2eproto
